title: Cozying.ai
description: Capstone 2025 Team 12
remote_theme: just-the-docs/just-the-docs

url: "https://kookmin-sw.github.io/capstone-2025-12/"

aux_links:
  GitHub Repository: https://github.com/kookmin-sw/captone-2025
